### ISSUE TITLE
autogenerate the solution.csv based on the creator inputs

### ISSUE THREAD

**Issue by abhishekkrthakur** [huggingface/competitions#13]
well, she's a beauty ! i've been testing and enjoying all the new features and the competition creators, they are great.

![image](https://github.com/huggingface/competitions/assets/18212928/65a77b99-641d-4b50-9578-f8481401af76)

so here it's a script competition with custom metrics, and i did add a solution.csv with correct headers, but the submission input accepts only two fields so there's a mismatch i think (my own hypothesis :-) ) 

one suggestion is to also autogenerate the solution.csv based on the creator inputs , and then generate the solution input fields i guess plain text for inputs , but i'm not sure and perhaps it's more clear simply to create the solution.csv directly based on the two current fields of the custom metric's solution submission.

the second one works for me fine, i'll try to modify the csv accordingly now and see.

_Originally posted by @Josephrp in https://github.com/huggingface/competitions/issues/9#issuecomment-1907957526_

**Comment by Josephrp** [comment]
so i found success with the workaround for this cited about.

submission.csv : 

```json
id,model,description
1,tonic/model,i does math
```
and this should be in the configuration file and submission.csv 
![image](https://github.com/huggingface/competitions/assets/18212928/5c9a8128-72aa-4015-9ade-98601e170f30)

It might be okay to fix these collumns , the contest owner simply parses the text strings returned according to his requirements.
