### ISSUE TITLE
What format should `script.py` be in?

### ISSUE THREAD

**Issue by trtd56** [huggingface/competitions#15]
I am currently creating script competitions and made a provisional submission script as follows for testing, but the submission attempt failed.

```python
import pandas as pd

df = pd.DataFrame([(f"testid{i:04}", 0) for i in range(100)], columns=["id", "pred"])
df.to_csv("submission.csv", index=None)
```

The competition's repository generated `submission_info/`, but `submissions/` were not generated.
The log stated `Empty DataFrame`, so I suspect that submission.csv was not generated correctly. What format should script.py be in?

**Comment by abhishekkrthakur** [comment]
if you have created a script competition, you need to submit a model repo containing script.py. the script.py should generate a file called `submission.csv`. seems like you did it right or did i miss something? could you please share the competition dataset repo and space so i take a deeper look?

**Comment by trtd56** [comment]
Thank you!

Sure, I have submitted a model repo containing script.py
[trtd56/compe_test_v1](https://huggingface.co/trtd56/compe_test_v1/blob/main/script.py)

Here is the repository for my competition.
https://huggingface.co/spaces/ai-shift/AIShiftTestCompetition

**Comment by abhishekkrthakur** [comment]
it seems like it has processed the submission but they seem to have failed: https://huggingface.co/datasets/ai-shift/AIShiftTestCompetition/blob/main/submission_info/6678945c-5268-47c7-8ee5-961820abc4e0.json. i cannot see the logs as the evaluation spaces have been deleted. could you make a submission and keep the evaluation space?

**Comment by trtd56** [comment]
Ah, my apologies. I have now made a new submission.

**Comment by abhishekkrthakur** [comment]
okay. i found the issue. fixing it right away!

**Comment by abhishekkrthakur** [comment]
okay. its working now. apologies for the inconvenience.
please note, you will need to change the metric in conf.json from `accuracy` to `accuracy_score`. this is another issue where names are not mapping properly. ill fix it soon too :) 
thank you for reporting this.

**Comment by abhishekkrthakur** [comment]
please let me know if it works for you now and i can close this issue :)

**Comment by trtd56** [comment]
Thank you!
It seems that the file has been added to submissions/, but looking at the "status" in submission_info/, it appears to be "failed".
The Leaderboard is not displayed.

**Comment by abhishekkrthakur** [comment]
> please note, you will need to change the metric in conf.json from accuracy to accuracy_score. this is another issue where names are not mapping properly. ill fix it soon too :)

did you make this change?

**Comment by trtd56** [comment]
No worries at all!
I am very grateful for your prompt response!

After rebooting and trying to submit again, it seems to have been successful. I was able to confirm the previous failed submissions as well.


|||
|--|--|
|<img width="1348" alt="スクリーンショット 2024-01-26 22 11 29" src="https://github.com/huggingface/competitions/assets/5457315/6ab63e69-41b3-4dc7-9f8a-fe10a92d3ed1">|<img width="610" alt="スクリーンショット 2024-01-26 22 11 21" src="https://github.com/huggingface/competitions/assets/5457315/c4ed03fb-b265-4ca1-9b5f-5a9c5b85a56f">|

Thank you very much!!!

**Comment by abhishekkrthakur** [comment]
great! im looking forward to the competition!
