### ISSUE TITLE
Where should the test data be placed?

### ISSUE THREAD

**Issue by trtd56** [huggingface/competitions#16]
I might have a silly question, but could you help me?

For a script competition, it is said that "test data can be hidden from the participants." but where should the test data be placed?

I can't seem to see it from the space where [script.py](http://script.py/) is running, even if I place it in the competition's dataset.

**Comment by trtd56** [comment]
Thank you for your reply!

I tried adding the DATASET parameter, but an error occurs upon submission.

```
ERROR:    Traceback (most recent call last):
  File "/app/env/lib/python3.10/site-packages/starlette/routing.py", line 705, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/app/env/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/app/competitions/api.py", line 92, in lifespan
    process_pid = run_evaluation(params=PARAMS)
  File "/app/competitions/utils.py", line 45, in run_evaluation
    params = EvalParams(**params)
  File "/app/env/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for EvalParams
dataset
  Field required [type=missing, input_value={'competition_id': 'ai-sh...v1', 'time_limit': 3600}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```

I deleted the DATASET and tried submitting again, but the same error occurs.

Did I cause any specific issues? Should I recreate the Competition?

**Comment by abhishekkrthakur** [comment]
you can factory rebuild the competition space. this issue has now been fixed. sorry, i forgot to notify here.

**Comment by trtd56** [comment]
No problem;)
I've confirmed that it's been fixed.

Thank you!
