### ISSUE TITLE
Error when using the multiple evaluation metric

### ISSUE THREAD

**Issue by shangfenghuang** [huggingface/competitions#19]
![image](https://github.com/huggingface/competitions/assets/45654745/c61f7300-20a6-42ed-865e-2a72da7fcf50)

![image](https://github.com/huggingface/competitions/assets/45654745/d5ad4608-f3d9-4e5a-82f2-67823d9121f4)

Question 1: how to delete the pulic score in leaderboard
Question 2: My metric name is added a prefixed

**Comment by abhishekkrthakur** [comment]
this will be fixed in next release

**Comment by abhishekkrthakur** [comment]
discussion going on in #20
