### ISSUE TITLE
Better metric and leaderboard management

### ISSUE THREAD

**Issue by shangfenghuang** [huggingface/competitions#20]
Can I modify the source code, e.g. index.html, app.py, etc ?

**Comment by abhishekkrthakur** [comment]
No. why would you want to do that? Are you missing a feature? Then please let us know.

**Comment by shangfenghuang** [comment]
Because there's a lot wrong with that.

For example: 

"public_score": {
  | "score": 1.0,
  | "En_offset": 0.0,
  | "En_CP": 1.0,
  | "En_CR": 1.0,
  | "En_CF1": 1.0,
  | "Ta_offset": 0.0,
  | "Ta_CP": 1.0,
  | "Ta_CR": 1.0,
  | "Ta_CF1": 1.0
  | },

If the first metric name is not 'score', the my_submissions function doesn't work.

Leaderboard.

The public score is equal to 1 and stand the first place, so that it can't rank the submission

**Comment by shangfenghuang** [comment]
Can these problems be fixed soon? We want to use the hugging face to hold the CVPR workshop competition. It's a bit of an emergency.

**Comment by abhishekkrthakur** [comment]
if you read the docs you will know why. anyways. there needs to be a score to rank the participants and it cant be done randomly, right? so we choose one from your multiple metrics alphabetically. if you feel something is incorrect, you can always open a pull request and contribute to fix it instead. 


id also request you not to open multiple issues concerning the same thing. ive also responded to you in your other issue. we will handle public_score better in next release.

**Comment by abhishekkrthakur** [comment]
it will be addressed today.

**Comment by shangfenghuang** [comment]
Thanks.  I would suggest using the first metric names as public scores rather than alphabetical order. It's the same method that should be used in My_submissions.

Thanks in advance.  I apologize if my urgency has come across as impolite.

"public_score": {
  | "score": 1.0,
  | "En_offset": 0.0,
  | "En_CP": 1.0,
  | "En_CR": 1.0,
  | "En_CF1": 1.0,
  | "Ta_offset": 0.0,
  | "Ta_CP": 1.0,
  | "Ta_CR": 1.0,
  | "Ta_CF1": 1.0
  | },

**Comment by abhishekkrthakur** [comment]
No worries. Apologies it caused an inconvenience. We are already working on it and will push the changes in a few hours after a few tests. We will either choose the first metric or it could be specified in conf.json as to which metric should be chosen for ranking. sounds good?

**Comment by shangfenghuang** [comment]
yeah, it's pretty good. It's probably the best solution.

**Comment by shangfenghuang** [comment]
Another friendly reminder.

solution = hf_hub_download(
        repo_id=params.competition_id,
        filename="",
        use_auth_token=params.token,
       # token = params.token,
        repo_type="dataset",
    )

Maybe it's my version, the token may need to be replaced with use_auth_token.
But I'm not sure if my version is the latest, but this replacement in competition project is working!

**Comment by shangfenghuang** [comment]
0.10.1.  But when I push the code to my project, it does work. I don't know why

**Comment by abhishekkrthakur** [comment]
This issue has now been resolved. You will be able to see the updated docs and use the new version after 20mins. If you have already created a competition space, please go to settings and factory rebuild. note: wait 20 mins for everything to be deployed properly.

**Comment by shangfenghuang** [comment]
GooD Job！！！！ Thanks, Thanks, Thanks, Thank, Thanks.

Another friendly reminder.
solution_file = hf_hub_download(
        repo_id=params.competition_id,
        filename="solution.csv",
        token=params.token,
        repo_type="dataset",
    )

Actually, when the token is not correct and filename and competition_id are correct, the code doesn't work but the error message still output the URL link of the input filename. When you click the URL，you can download the file. However, it can cause the ground truth label leakage. It's fatal to the competition.

For example, when using the multiple metrics, the metric.py must be created. Additionly, the competition_id is generally the name of the private project if I don't change it. The competition_id is same the competition name. For now, we can get the competition_id and filename(metri.py), so I can download the metric.py. As you know, the metric.py code will include a function that will get the ground truth file. So, you can find the ground truth file name from metric.py. 

![image](https://github.com/huggingface/competitions/assets/45654745/b87f637b-d1d9-4b4f-b660-5480859352a9)

**Comment by abhishekkrthakur** [comment]
the token must always be correct. without it, we wont be able to access the datasets for evaluation purposes. 

also, the logs are only visible to the organizers in hf spaces. the private dataset can never be accessed by anyone without the write token of the organizers. i suggest you to create a test user who is not a part of the organization and submit using that user instead. then you wont be able to see any logs :) please let me know if that helps or if you have any other concerns.

**Comment by abhishekkrthakur** [comment]
your metric.py, solution.csv and all other files are always in a private repo. when a user submits, they dont have access to that private repo. script competitons run script.py without internet. so there is no way targets can leak. but if im missing something, please let me know and we'll solve it.

**Comment by shangfenghuang** [comment]
Now I don't have any problems.

**Comment by abhishekkrthakur** [comment]
glad to know. in case of other issues or feature requests, please create a new issue and it shpuldybe resolved promptly. thank you for this issue.
