### ISSUE TITLE
Modify the describe of my submissions

### ISSUE THREAD

**Issue by shangfenghuang** [huggingface/competitions#22]
![image](https://github.com/huggingface/competitions/assets/45654745/a6d9257c-5dab-486e-bf68-ecffc81b43c0)

Could I change it?

**Comment by abhishekkrthakur** [comment]
it seems to be quite explanatory, no? what would you like to have instead?

**Comment by shangfenghuang** [comment]
Because we don't need to the private leaderboarad and the test data isn't divided into public and private splits. In my competition, the dataset is divided into training and testing set. For the training set, the participants have the ground truth of training set, so they can evaluate the results themselves. In the leaderboard, we just evaluate the testing set. So we just have public leaderboard. In other ways, the public and private are the same. So these words may mislead the participants that the final result of our competition depends on the private leaderboard. 

It would actually be better if those words could be modified. If not, it doesn't matter.

**Comment by abhishekkrthakur** [comment]
your competition design seems very flawed or we are not able to explain properly in docs. contact us at autotrain@hf.co so we can schedule a meeting to explain further.

**Comment by abhishekkrthakur** [comment]
if your public and private leader board is the same, everyone will also overfit on the data and the solutions will not be generalizable. is this what you want?
