### ISSUE TITLE
Feature request: display commit hash on submission_info

### ISSUE THREAD

**Issue by Polariche** [huggingface/competitions#28]
Hi,

enjoying your work so far! I want to make a small suggestion for 'script' competitions

currently, my submission_info displays the following:
```
{
"datetime": "2024-05-28 05:53:55",
"submission_id": "0fb3273c-ede2-4dd6-8dae-7fdb210e269a",
"submission_comment": "",
"submission_repo": "<omitted>/dummy",
"space_id": "<omitted>/comp-0fb3273c-ede2-4dd6-8dae-7fdb210e269a",
"submitted_by": "<omitted>",
"status": 3,
"selected": true,
"public_score": {
"accuracy_score": 0.4444444444444444
},
"private_score": {
"accuracy_score": 0.45454545454545453
}
}
```

I found it rather hard to trace back the submitted script, since it is prone to change per every submission.
would it be possible to add **commit hash** to submission_info?

**Comment by abhishekkrthakur** [comment]
will be fixed.

**Comment by abhishekkrthakur** [comment]
now, in this case, the submission id is the commit hash
