### ISSUE TITLE
Using other files instead of CSV as the solution file

### ISSUE THREAD

**Issue by HuangZhen02** [huggingface/competitions#30]
Hi, I would like to know if it supports using files like JSON instead of CSV as the solution file.

**Comment by HuangZhen02** [comment]
Cool, I'm planning to use the competition module to host my own leaderboard competition and want to confirm some functionalities. By the way, I also want to ask, is it supported to use custom metrics that require additional Python packages (e.g. scipy) for evaluation?

**Comment by abhishekkrthakur** [comment]
yes. please see docs: hf.co/docs/competitons

**Comment by HuangZhen02** [comment]
However, I don't seem to find any instructions in the document on how to set up one's own environment (installing their own libraries) for generic competitions in https://huggingface.co/docs/competitions/en/custom_metric 

Is it only supported by script competitions?

**Comment by abhishekkrthakur** [comment]
im not sure if i understand. what do you mean by custom environment?


custom metrics are supported for both

**Comment by HuangZhen02** [comment]
OK, what I mean is that I want to create a generic competition, and when customizing the metrics, I want to leverage some python packages(which need pip install..)  to assist in evaluating the answers.

**Comment by abhishekkrthakur** [comment]
use requirements.txt in the created repo.

**Comment by HuangZhen02** [comment]
Nice. Does this mean that the generic competition will install some dependencies listed in the dataset's requirements.txt before conducting the evaluation?

**Comment by abhishekkrthakur** [comment]
yes. please try and read docs. set up competiton, if something doesnt work, create issue here.

issues are not for confirming what works and what doesnt :)
