### ISSUE TITLE
Error creating a competition

### ISSUE THREAD

**Issue by Suryavf** [huggingface/competitions#33]
Hello
I am trying to create a competition for my organization from the https://huggingface.co/spaces/competitions/create page.
I created a token with all access, however I am getting an error message.
![image](https://github.com/user-attachments/assets/3311e7b8-2efd-4ad2-bfe3-1ad171311647)
What could be the cause of the error?

**Comment by abhishekkrthakur** [comment]
payment method is no longer a requirement. probable cause seems like token doesnt have write access to the selected organization.
