### ISSUE TITLE
Change pip version in submission space

### ISSUE THREAD

**Issue by mh0797** [huggingface/competitions#35]
Hi,
Is there a way to change the pip version (and maybe also the python version) for the submission spaces of the competition?
I don't mean the actual competition space; instead, I mean the space that is created upon submission (named "comp-<token of submission>").

**Comment by abhishekkrthakur** [comment]
pip version can be updated for all. no problem. python cannot. which python version do you prefer and why? :)

**Comment by mh0797** [comment]
How exactly can I update the pip version?
Changing the Python version is not a priority for now, I was just curious about this :D

**Comment by abhishekkrthakur** [comment]
we can update pip to latest by rebuilding the docker

**Comment by abhishekkrthakur** [comment]
you can also install custom packages by creating a requirements.txt file in the competition config repo. so, thats another way :)

**Comment by mh0797** [comment]
I actually want to downgrade it from 24.2 to 24.0 because one dependency in the requirements file cannot be installed with the latest version.

Unfortunately, I cannot simply add another pip version to the requirements.txt as this will not prevent the error because then pip 24.2 will install all dependencies (including pip 24.0).

I need an option to make sure that a different pip version is already installed *before* the requirements are installed.

**Comment by abhishekkrthakur** [comment]
could you please share which dependency doesn't work?

**Comment by mh0797** [comment]
We cannot install `omegaconf==2.1.0rc1` (see [here](https://github.com/omry/omegaconf/issues/1187)) which is a dependency of `hydra-core==1.1.0rc1`

**Comment by JacobLinCool** [comment]
You can upgrade pip using `pre-requirements.txt`.
ref: https://huggingface.co/docs/hub/spaces-dependencies#adding-your-own-dependencies

**Comment by mh0797** [comment]
Unfortunately the pre-requirements file only affects the leaderboard space but not the individual spaces created to run submissions. 

In the meantime we were able to remove this dependency.
Still, I believe for future it would be great to add the feature to control the pip version also of the submission spaces.

we can close this for now.

**Comment by abhishekkrthakur** [comment]
Thank you.

Once you are done setting up the competition, please let me know and we can put it on the competitions page and share on socials.

**Comment by mh0797** [comment]
Great, here’s the link:
https://huggingface.co/spaces/AGC2024-P/e2e-driving-navsim
