### ISSUE TITLE
Submission ID is not updating when Hub Model is the same

### ISSUE THREAD

**Issue by lennart-maack** [huggingface/competitions#38]
First of all, thank you for creating this project. I think it's really great. It is easy to implement and offers many possibilities to customize the competition to your own needs.

Now to my problem/observation:

I have noticed that the submission ID remains the same for a new submission if you have not changed your hub model. This means that the submission remains in “Pending” status throughout and there is no “Failed” or “Success” status in the end. Maybe it makes sense to provide an error case for this.

![image](https://github.com/user-attachments/assets/0d2ba0f8-9f3d-4c5d-b5ca-03c574607460)

**Comment by abhishekkrthakur** [comment]
fixed. the image is building. after ~10mins, a factory rebuild on competition repo will use the applied fix
