### ISSUE TITLE
How to modify the competition

### ISSUE THREAD

**Issue by dakshvar22** [huggingface/competitions#40]
Hi! I created a new competition using the [tool given here](https://huggingface.co/spaces/competitions/create). All good up till here.
Then I had the space automatically running. To modify the competition, I cloned the repository of the space locally with the command given on the UI
```
git clone https://huggingface.co/spaces/cmdgentest/commandgen
```
When I inspected the contents, it had only two files - `Dockerfile` and `README.md`. This was surprising as i expected the files mentioned [here](https://huggingface.co/docs/competitions/en/competition_repo).
However, I still created these files myself and pushed the changes to the spaces repo. Once the space was restarted and running, I still wasn't able to see the changes I made.

At this point I am confused where exactly should I put files like `conf.json` in my case.

**Comment by ktrapeznikov** [comment]
These files should be in the dataset repo from what I understand
