### ISSUE TITLE
Recommended way to install dependencies for a script submission

### ISSUE THREAD

**Issue by ktrapeznikov** [huggingface/competitions#43]
what is the recommended way to install dependencies (like addition python packages, etc. ) of a script submission? Should everything be called from the `script.py`?

**Comment by abhishekkrthakur** [comment]
you can create a requirements.txt inside the competition info repo :) i see this is undocumented. ill add it to the docs.

**Comment by ktrapeznikov** [comment]
is there a way to have a different requirements file per submission? I can imagine that one model may have different requirements from another.

**Comment by abhishekkrthakur** [comment]
no. the organizers set the requirements to provide equal opportunities to all participants. if a participant needs custom requirements, they have to package them inside the model submisson repo (alongside script.py) as wheels/folders/etc and then add them to path or install inside script.py. 

note: internet is disabled when script.py is run.
