### ISSUE TITLE
Gated user access to submit to public competition

### ISSUE THREAD

**Issue by ktrapeznikov** [huggingface/competitions#44]
Is there a way to enable gated user access before one is allowed to make a submission? In the same way some models and datasets, require users to fill out a request form and agree to terms, etc.

I am interested in doing this for a script competition.

**Comment by abhishekkrthakur** [comment]
you can have the competition dataset as gated. or did i misunderstand your question? :)

**Comment by ktrapeznikov** [comment]
If it's a script competition, the dataset is already private. if I make the completion space public then anyone can submit. I'd like a way to control who can submit.

**Comment by abhishekkrthakur** [comment]
you can move competition space to an organization and make it private. then add people to the organization who can see the private competition space and they will be the only ones who can make submission.

**Comment by ktrapeznikov** [comment]
ah ok thanks

**Comment by yutanakamura-tky** [comment]
@ktrapeznikov @abhishekkrthakur I'm suffering from the same issue; Even with upgrading to Hugging Face Enterprize and applying Resource Groups, I couldn't make the competitions visible only to participants while keeping the private dataset and private LB discarded to participants.

**Comment by abhishekkrthakur** [comment]
if there is demand, we can make a feature where competition is public but users need to be manually verified (or added to a list) in order to make a submission. does that work for you?

**Comment by yutanakamura-tky** [comment]
@abhishekkrthakur Thank you for your suggestion and it will greatly help us! Competitions hosted as a part of an academic conference, like ours, typically mandate registration to make sure that participants submit their solution paper to, and make a presentation in, the conference.

**Comment by VVeiCao** [comment]
Follow-up question regarding the feature: Is it added?
