### ISSUE TITLE
Why so many dependencies

### ISSUE THREAD

**Issue by julien-blanchon** [huggingface/competitions#8]
I'm not sure to get the purpose of this project but it seems that many requirements are not even use in the codebase. Why would we need `bitsandbytes`, `diffusers`, `optuna`, `peft`, `sklearn`, `transformers`, `xgboost` ... for managing competitions ?

**Comment by abhishekkrthakur** [comment]
we'll remove some dependencies in near future. currently it has been done to create an environment for script competitons. however, soon there will be a ui space to create competitions and you dont need to worry about any installations to create competitons.

**Comment by abhishekkrthakur** [comment]
creator space is up. pip installation isnt required anymore. issue resolved
